### ISSUE TITLE
Answer Correct-Marked Wrong

### ISSUE THREAD

**Issue by heather-tech** [learn-co-curriculum/phase-1-quiz-communicating-with-the-server#3]
### Canvas Link

https://learning.flatironschool.com/courses/5855/quizzes/40919

### Concern

![Screen Shot 2023-03-04 at 7 40 23 AM](https://user-images.githubusercontent.com/103140932/222901742-02993743-3b8a-44b3-a992-7652ca538876.png)

### Additional Context

I just saw the comma was already included in the original.

**Comment by lizbur10** [comment]
Hi @heather-tech ! Thanks for submitting this issue.

I'm not entirely sure I understand the problem. I believe the answer identified as correct is accurate, because the blank in the code snippet has a comma after it, so adding `JSON.stringify(formData),` would result in two commas rather than one. 

I'm going to go ahead and close this issue but please feel free to reopen it if I've misunderstood. 💙
